# All the tasks to system thread

TASK_SYSTEM_REBOOT = 0x101
TASK_SYSTEM_ACK = 0x102

TASK_SYSTEM_DEFAULT = 0x201
TASK_SYSTEM_RUNNING = 0x202

TASK_SYSTEM_STK_BUY      = 0x2F0
TASK_SYSTEM_STK_BUY_CLR  = 0x2F1
TASK_SYSTEM_STK_SELL     = 0x2F2
TASK_SYSTEM_STK_SELL_CLR = 0x2F3
TASK_SYSTEM_STK_CRT      = 0x2F4
TASK_SYSTEM_STK_CRT_CLR  = 0x2F5

